// ことばパズルの問題データ
// 画像は 'images/inu.png' のように、ご自身で用意した画像へのパスに書き換えてください。
// 今は仮の画像が表示されるようになっています。
const puzzles = [
    { hint: 'この どうぶつ なあに？', answer: 'いぬ', image: 'assets/images/kotobapuzzle/いぬ.png' },
    { hint: 'この どうぶつ なあに？', answer: 'ねこ', image: 'assets/images/kotobapuzzle/ねこ.png' },
    { hint: 'おそら を とぶよ', answer: 'ひこうき', image: 'assets/images/kotobapuzzle/ひこうき.png' },
    { hint: 'あかい くだもの', answer: 'りんご', image: 'assets/images/kotobapuzzle/りんご.png' },
    { hint: 'きいろい くだもの', answer: 'バナナ', image: 'assets/images/kotobapuzzle/バナナ.png' },
    { hint: 'うみの なかま', answer: 'イルカ', image: 'assets/images/kotobapuzzle/イルカ.png' },
    { hint: 'のりもの だよ', answer: 'でんしゃ', image: 'assets/images/kotobapuzzle/でんしゃ.png' },
    { hint: 'はな が ながい どうぶつ', answer: 'ぞう', image: 'assets/images/kotobapuzzle/ぞう.png' },
    { hint: 'くび が ながい どうぶつ', answer: 'きりん', image: 'assets/images/kotobapuzzle/きりん.png' },
    { hint: 'どうぶつ の おうさま', answer: 'ライオン', image: 'assets/images/kotobapuzzle/ライオン.png' },
    { hint: 'ぴょんぴょん はねるよ', answer: 'うさぎ', image: 'assets/images/kotobapuzzle/うさぎ.png' },
    { hint: 'ささを たべる どうぶつ', answer: 'パンダ', image: 'assets/images/kotobapuzzle/パンダ.png' },
    { hint: 'あかい くだもの', answer: 'いちご', image: 'assets/images/kotobapuzzle/いちご.png' },
    { hint: 'ふゆに たべる くだもの', answer: 'みかん', image: 'assets/images/kotobapuzzle/みかん.png' },
    { hint: 'みんなを はこぶ のりもの', answer: 'バス', image: 'assets/images/kotobapuzzle/バス.png' },
    { hint: 'まちを はしる のりもの', answer: 'くるま', image: 'assets/images/kotobapuzzle/くるま.png' },
    { hint: 'はやい のりもの', answer: 'しんかんせん', image: 'assets/images/kotobapuzzle/しんかんせん.png' },
    { hint: 'じかんを おしえてくれる', answer: 'とけい', image: 'assets/images/kotobapuzzle/とけい.png' },
    { hint: 'あさ ごはんに たべる', answer: 'パン', image: 'assets/images/kotobapuzzle/パン.png' },
    { hint: 'おたんじょうびに たべる', answer: 'ケーキ', image: 'assets/images/kotobapuzzle/ケーキ.png' },
    { hint: 'ちからもちの どうぶつ', answer: 'ゴリラ', image: 'assets/images/kotobapuzzle/ゴリラ.png' },
    { hint: 'うちゅうへ とんでいく', answer: 'ロケット', image: 'assets/images/kotobapuzzle/ロケット.png' },
    { hint: 'しましま の どうぶつ', answer: 'とら', image: 'assets/images/kotobapuzzle/とら.png' },
    { hint: 'ばななが すきな どうぶつ', answer: 'さる', image: 'assets/images/kotobapuzzle/さる.png' },
    { hint: 'さむいところに すむ とり', answer: 'ペンギン', image: 'assets/images/kotobapuzzle/ペンギン.png' },
    { hint: 'あかい やさい', answer: 'トマト', image: 'assets/images/kotobapuzzle/トマト.png' },
    { hint: 'なつに たべる おおきな くだもの', answer: 'すいか', image: 'assets/images/kotobapuzzle/すいか.png' },
    { hint: 'えいがを みる きかい', answer: 'テレビ', image: 'assets/images/kotobapuzzle/テレビ.png' },
    { hint: 'あめのひに さすもの', answer: 'かさ', image: 'assets/images/kotobapuzzle/かさ.png' },
    { hint: 'あたまに かぶるもの', answer: 'ぼうし', image: 'assets/images/kotobapuzzle/ぼうし.png' },
    { hint: 'うみを すすむ のりもの', answer: 'ふね', image: 'assets/images/kotobapuzzle/ふね.png' },
    { hint: 'けいさつかんが のる くるま', answer: 'パトカー', image: 'assets/images/kotobapuzzle/パトカー.png' },
    { hint: 'ひるまに そらにでる', answer: 'たいよう', image: 'assets/images/kotobapuzzle/たいよう.png' },
    { hint: 'よるに そらにでる', answer: 'つき', image: 'assets/images/kotobapuzzle/つき.png' },
    { hint: 'はを みがくときに つかう', answer: 'ハブラシ', image: 'assets/images/kotobapuzzle/ハブラシ.png' },
    { hint: 'ペダルをこいで すすむ', answer: 'じてんしゃ', image: 'assets/images/kotobapuzzle/じてんしゃ.png' },
    { hint: 'びょうにんを はこぶ くるま', answer: 'きゅうきゅうしゃ', image: 'assets/images/kotobapuzzle/きゅうきゅうしゃ.png' },
    { hint: 'ひを けす くるま', answer: 'しょうぼうしゃ', image: 'assets/images/kotobapuzzle/しょうぼうしゃ.png' },
    { hint: 'めに かけるもの', answer: 'めがね', image: 'assets/images/kotobapuzzle/めがね.png' },
    { hint: 'もじを かく どうぐ', answer: 'えんぴつ', image: 'assets/images/kotobapuzzle/えんぴつ.png' },
    { hint: 'もじを けす どうぐ', answer: 'けしごむ', image: 'assets/images/kotobapuzzle/けしごむ.png' },
    { hint: 'こうらがある どうぶつ', answer: 'かめ', image: 'assets/images/kotobapuzzle/かめ.png' },
    { hint: 'うみで いちばん おおきい', answer: 'くじら', image: 'assets/images/kotobapuzzle/くじら.png' },
    { hint: 'むらさきの くだもの', answer: 'ぶどう', image: 'assets/images/kotobapuzzle/ぶどう.png' },
    { hint: 'みどりの あみあみ くだもの', answer: 'メロン', image: 'assets/images/kotobapuzzle/メロン.png' },
    { hint: 'おとを だす がっき', answer: 'ピアノ', image: 'assets/images/kotobapuzzle/ピアノ.png' },
    { hint: 'しゃしんを とる きかい', answer: 'カメラ', image: 'assets/images/kotobapuzzle/カメラ.png' },
    { hint: 'きかいで うごく にんぎょう', answer: 'ロボット', image: 'assets/images/kotobapuzzle/ロボット.png' },
    { hint: 'はるに さく はな', answer: 'チューリップ', image: 'assets/images/kotobapuzzle/チューリップ.png' },
    { hint: 'たいようの ほうを むく はな', answer: 'ひまわり', image: 'assets/images/kotobapuzzle/ひまわり.png' },
    { hint: 'おおきな くちの どうぶつ', answer: 'かば', image: 'assets/images/kotobapuzzle/かば.png' },
    { hint: 'はなのうえに つのが ある', answer: 'さい', image: 'assets/images/kotobapuzzle/さい.png' },
    { hint: 'もり に すむ どうぶつ', answer: 'しか', image: 'assets/images/kotobapuzzle/しか.png' },
    { hint: 'はちみつが すきな どうぶつ', answer: 'くま', image: 'assets/images/kotobapuzzle/くま.png' },
    { hint: 'やまに すむ どうぶつ', answer: 'きつね', image: 'assets/images/kotobapuzzle/きつね.png' },
    { hint: 'おなかが ぽんぽこ', answer: 'たぬき', image: 'assets/images/kotobapuzzle/たぬき.png' },
    { hint: 'にょろにょろ うごく', answer: 'へび', image: 'assets/images/kotobapuzzle/へび.png' },
    { hint: 'みずべに すむ おおきな どうぶつ', answer: 'わに', image: 'assets/images/kotobapuzzle/わに.png' },
    { hint: 'うみの こわい さかな', answer: 'さめ', image: 'assets/images/kotobapuzzle/さめ.png' },
    { hint: 'あしが ８ぽん', answer: 'たこ', image: 'assets/images/kotobapuzzle/たこ.png' },
    { hint: 'あしが １０ぽん', answer: 'いか', image: 'assets/images/kotobapuzzle/いか.png' },
    { hint: 'うみでとれる おいしいもの', answer: 'えび', image: 'assets/images/kotobapuzzle/えび.png' },
    { hint: 'よこに あるく', answer: 'かに', image: 'assets/images/kotobapuzzle/かに.png' },
    { hint: 'おれんじいろの やさい', answer: 'にんじん', image: 'assets/images/kotobapuzzle/にんじん.png' },
    { hint: 'みどりで ながい やさい', answer: 'きゅうり', image: 'assets/images/kotobapuzzle/きゅうり.png' },
    { hint: 'きると なみだがでる やさい', answer: 'たまねぎ', image: 'assets/images/kotobapuzzle/たまねぎ.png' },
    { hint: 'にがい みどりの やさい', answer: 'ピーマン', image: 'assets/images/kotobapuzzle/ピーマン.png' },
    { hint: 'きの かたちの やさい', answer: 'ブロッコリー', image: 'assets/images/kotobapuzzle/ブロッコリー.png' },
    { hint: 'すっぱい きいろい くだもの', answer: 'レモン', image: 'assets/images/kotobapuzzle/レモン.png' },
    { hint: 'ぴんくいろの くだもの', answer: 'もも', image: 'assets/images/kotobapuzzle/もも.png' },
    { hint: 'くだものを しぼった のみもの', answer: 'ジュース', image: 'assets/images/kotobapuzzle/ジュース.png' },
    { hint: 'うしから とれる しろい のみもの', answer: 'ぎゅうにゅう', image: 'assets/images/kotobapuzzle/ぎゅうにゅう.png' },
    { hint: 'おとなが のむ にがい のみもの', answer: 'コーヒー', image: 'assets/images/kotobapuzzle/コーヒー.png' },
    { hint: 'にほんの ひとが よくのむ', answer: 'おちゃ', image: 'assets/images/kotobapuzzle/おちゃ.png' },
    { hint: 'なつに たべる つめたい おかし', answer: 'アイスクリーム', image: 'assets/images/kotobapuzzle/アイスクリーム.png' },
    { hint: 'あまい ちゃいろの おかし', answer: 'チョコレート', image: 'assets/images/kotobapuzzle/チョコレート.png' },
    { hint: 'さんかくの かたちをした ごはん', answer: 'おにぎり', image: 'assets/images/kotobapuzzle/おにぎり.png' },
    { hint: 'てを あげて とめる のりもの', answer: 'タクシー', image: 'assets/images/kotobapuzzle/タクシー.png' },
    { hint: 'にりんで はしる のりもの', answer: 'オートバイ', image: 'assets/images/kotobapuzzle/オートバイ.png' },
    { hint: 'かぜで うごく ふね', answer: 'ヨット', image: 'assets/images/kotobapuzzle/ヨット.png' },
    { hint: 'ぷろぺらが まわる のりもの', answer: 'ヘリコプター', image: 'assets/images/kotobapuzzle/ヘリコプター.png' },
    { hint: 'すわるための かぐ', answer: 'いす', image: 'assets/images/kotobapuzzle/いす.png' },
    { hint: 'べんきょうする ときに つかう', answer: 'つくえ', image: 'assets/images/kotobapuzzle/つくえ.png' },
    { hint: 'よるに ねる ばしょ', answer: 'ベッド', image: 'assets/images/kotobapuzzle/ベッド.png' },
    { hint: 'へやの でいりぐち', answer: 'ドア', image: 'assets/images/kotobapuzzle/ドア.png' },
    { hint: 'そとを みるためのもの', answer: 'まど', image: 'assets/images/kotobapuzzle/まど.png' },
    { hint: 'かみを きる どうぐ', answer: 'はさみ', image: 'assets/images/kotobapuzzle/はさみ.png' },
    { hint: 'かみを くっつける どうぐ', answer: 'のり', image: 'assets/images/kotobapuzzle/のり.png' },
    { hint: 'ものがたりが かいてある', answer: 'ほん', image: 'assets/images/kotobapuzzle/ほん.png' },
    { hint: 'あしに はくもの', answer: 'くつ', image: 'assets/images/kotobapuzzle/くつ.png' },
    { hint: 'くつの したに はくもの', answer: 'くつした', image: 'assets/images/kotobapuzzle/くつした.png' },
    { hint: 'あしに はく ふく', answer: 'ズボン', image: 'assets/images/kotobapuzzle/ズボン.png' },
    { hint: 'おんなのこが はく ふく', answer: 'スカート', image: 'assets/images/kotobapuzzle/スカート.png' },
    { hint: 'ひらひら とぶ むし', answer: 'ちょう', image: 'assets/images/kotobapuzzle/ちょう.png' },
    { hint: 'めが おおきい むし', answer: 'とんぼ', image: 'assets/images/kotobapuzzle/とんぼ.png' },
    { hint: 'なつに なく むし', answer: 'せみ', image: 'assets/images/kotobapuzzle/せみ.png' },
    { hint: 'つのが ある かっこいい むし', answer: 'かぶとむし', image: 'assets/images/kotobapuzzle/かぶとむし.png' },
    { hint: 'ぼーるを ける すぽーつ', answer: 'サッカー', image: 'assets/images/kotobapuzzle/サッカー.png' },
    { hint: 'ぼーるを うつ すぽーつ', answer: 'やきゅう', image: 'assets/images/kotobapuzzle/やきゅう.png' },
    { hint: 'らけっとを つかう すぽーつ', answer: 'テニス', image: 'assets/images/kotobapuzzle/テニス.png' }
];